spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pitthungamaDB?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: Shan5054$$$
    jpa:
        hibernate:
            ddl-auto: create
            auto_quote_keyword : true
            database-platform: org.hibernate.dialect.MySQLDialect

    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        username: shanlaksh94@gmail.com
        password: mzuzxncsfkcevynx
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        test-connection: false
    autoconfigure:
        exclude:
            - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
            - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
            - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

app-config:
    thymeleaf-template-assets-path:

cloud:
    aws:
        region:
            static: ap-southeast-1
            auto: false
        stack:
            auto: false
        credentials:
            access-key: AKIAS75GJ5LXU7JQ6XOJ
            secret-key: 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

application:
    amazons3bucket:
        name: pitthungamabucket